CREATE TABLE Clientes (id_cli int(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,email TEXT NOT NULL,nick TEXT ,contrasenya TEXT ,nombre TEXT ,telefono INT(13));


CREATE TABLE direcciones (id_cli int(4) ,email TEXT  NOT NULL,direccion VARCHAR (50), numero int (10),puerta int (10) ,cp int (6) ,localidad VARCHAR(100));

CREATE TABLE detallePedido( id_Pedido INT (10)AUTO_INCREMENT PRIMARY KEY, estado VARCHAR(100) , productos VARCHAR(50), precio FLOAT (5));

CREATE TABLE productos( id_Producto INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) ,precio float(10) ,imagen TEXT ,stock int(10) ,categoria TEXT ,descripcion TEXT);



ALTER TABLE direcciones ADD FOREIGN KEY (id_cli) REFERENCES Clientes (id_cli);


INSERT INTO Clientes (email, nick, contrasenya,nombre,telefono) VALUES ("admin@gmail.com","admin","admin","admin","123455");
INSERT INTO Clientes (email, nick, contrasenya,nombre,telefono) VALUES ("usu1@gmail.com","usu1","1234","usu1","12345556");
INSERT INTO Clientes (email, nick, contrasenya,nombre,telefono) VALUES ("usu@gmail.com","usu","1234","usu","63987626");
INSERT INTO Clientes (email, nick, contrasenya,nombre,telefono) VALUES ("carlos@gmail.com","carlos","1234","carlos","63987626");

INSERT INTO direcciones (id_cli,email, direccion, numero,puerta,cp,localidad) VALUES ("1","admin@gmail.com","Juan de Garay","1","7","46016","Valencia");
INSERT INTO direcciones (id_cli,email, direccion, numero,puerta,cp,localidad) VALUES ( "2","usu1@gmail.com","Alquerias de Bellver","12","1","46015","Valencia");
INSERT INTO direcciones (id_cli,email, direccion, numero,puerta,cp,localidad) VALUES ("3","usu@gmail.com","Guillem","3","5","28001","Madrid");
INSERT INTO direcciones (id_cli,email, direccion, numero,puerta,cp,localidad) VALUES ("4","carlos@gmail.com","Quartell","7","10","46015","Valencia");

INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion) VALUES ("ZEUS",25.95,"https://http2.mlstatic.com/geek-vape-zeus-rta-tanque-electronico-D_NQ_NP_788887-MLM27853957685_072018-F.jpg",10,"RTA","Zeus es un RTA a prueba de fugas diseñado por Justin, Geekvape GM.
Diseñado para acomodar a todos los amantes de RTA, desde principiantes hasta veteranos, Zeus fue creado para ser fácil de usar a la vez que ofrece
sabor con flujo de aire 3D y elimina problemas de fuga mediante la implementación de un mejor flujo de aire superior.
La tapa superior Zeus ha incorporado el diseño de acceso rápido para facilitar el acceso a la recarga.
El mejor flujo de aire superior elimina las fugas al tiempo que proporciona una entrada más suave.
Sistema de recarga simplificado para un acceso rápido.
El flujo de aire 3D desde ambos lados e inferior produce un sabor sobresaliente.
Se incluyen dos puntas de goteo 510 y 810");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion) VALUES ("DRUGA",29.95,"https://images-na.ssl-images-amazon.com/images/I/411ro%2BqVoqL._SX425_.jpg",10,"RDA","Atomizador regenerador Druga de Augvape, un dripper espectacular, líder en el mercado frente a sus competidores por su relación calidad-precio absolutamente incomparable.Druga es un RDA que facilita las operaciones de regeneración gracias al utilizo del CSS (Clamp Snag System), un sistema de sujeción de abrazaderas que hará que la instalación de tus resistencias sea un juego de niños; tendrás la percepción de que montar una bobina nunca había sido tan fácil - Las grandes torretas Hydroscud permiten un montaje preciso de hilos de gran diámetro y se pueden tensar con las manos.Druga RDA está fabricado con materiales de alta calidad, cada pieza está curada hasta el mínimo detalle, especialmente la cubierta, que es realmente amplia y espaciosa, bañada en oro y te permite la inserción de una bobina de cualquier material.El gotero Druga tiene un diámetro de 24 mm, un drip tip muy largo de 810 (incluyendo un adaptador de 510), un pin 510 bañado en oro y un pin Bottom Feeder incluido en el kit también para ser utilizado con las cajas de Squonk Bottom Feeder.No hay mucho más que decir sobre este fantástico atomizador: bonito estáticamente, funcional, aireado gracias a las aperturas laterales (estilo Goon) y además asegura una excelente rendimiento aromático.El dripper que gusta a todos, principiantes y expertos.Un atomizador regenerador para probar; es necesario que lo tengas en tu colección de vapeo.Caracterásticas:Material: acero inoxidable 304 - Diámetro: 24 mm - Drip Tip 810 - Cubierta chapada en oro de 24 quilates - Clamp Snag System - Con Ultem Drip Tip y Derlin Drip Tip - Con pin chapado en oro y oin de acero inoxidable Squonk Bottom Feeder - El paquete Incluye:1 x Druga RDA + 1 x Pin BF + 1 x Derlin Drip Tip negro + 1 x Juego de anillas de repuesto + 1 x Llave hexagonal.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion) VALUES ("WASP NANO",9.95,"https://cdn.shopify.com/s/files/1/2233/7575/products/Oumier-Wasp-Nano-RDATodos_x700.jpg?v=1521523369",10,"RDA","Si buscas comprar un RDA barato, fácil de usar y que ofrezca un gran sabor y vapor Oumier Wasp Nano RDA es tu mejor elección. En un mundo donde las grandes RDA son la palabra, Oumier Wasp Nano RDA representa un cambio de ritmo. Es pequeño pero muy poderoso, solo 22mm de diámetro y 22,5mm de alto. Es increíble lo pequeóo y compacto que es.

Cuenta con doble flujo regulable de aire en los laterales y la plataforma de montaje para single coil está chapada en oro. Tiene una piscina decente y las abrazaderas y terminales son muy fáciles de usar. La plataforma, al igual que toda la configuración, es eficaz y está muy bien pensada. Además se puede usar como un RDA normal y como squonk con el pin BF incluido.

Tamaño: 22mm de diámetro y 22,5mm de largo (boquilla incluida). Rosca: 510");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("DROP",19.95,"https://www.elementvape.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/i/digiflavor_drop_24mm_rda_by_the_vapor_chronicles_build_deck_1.jpg",10,"RDA","Atomizador diseñado por The vapor chronicles, Drop RDA de digiflavor.
24mm de diametro y 4 orificios para los coils, montaje sencillo para coils grande.
Entrada de aire regulable y piscina amplia.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("ALMOND CARAMEL BLEND TOBACCO",4.95,"https://masquevapor.com/42369-large_default/almond-caramel-blend-tobacco-10ml-pack-alo-flavours.jpg",10,"LIQUIDO","Fragante y tradicional aroma tabaquil con un ligero toque de almendras.

");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("Nudge RDA ",4.95,"https://morethanvapersshop.es/wp-content/uploads/2019/01/authentic-wotofo-nudge-rda-rebuildable-dripping-atomizer-w-bf-pin-red-aluminum-316-stainless-steel-22mm-diameter-1-600x601.jpg",10,"RDA","Nudge RDA 22 es perfecto, con una entrada de aire muy agradable y una gran producción de vapor. Un gran acierto de Wotofo para este pequeño atomizador single coil con pin 510 y pin bottom feeder chapados en oro. La base con el deck es de acero y la campana de aluminio de grado aeronáutico. También lleva aislante peek capaz de soportar elevadas temperaturas. Además trae una segunda campana con una entrada de aire más pequeña que rinde de manera espectacular. El aire entra por los dos laterales y es conducido directamente a la resistencia para luego elevarse con todo el sabor y vapor hacia el drip.

Lleva boquilla 810 de resina y adaptador para boquillas 510. El pack incluye 2 campanas con diferentes aberturas de entrada de aire para satisfacer las preferencias personales. Lleva rosca 510 de acero inoxidable y funciona con mods comunes y bottom feeder o squonk.

Medidas: 22mm de diámetro y 32mm de largo (boquilla incluida).");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("ARMAGEDDON",49.95,"https://morethanvapersshop.es/wp-content/uploads/2018/12/apocalypse-rda-25mm-armageddon-mfg-2.jpg",10,"RDA","Armageddon Mfg Redemption RDA presenta su nuevo RDA, el Redemption. Este atomizador tiene un deck de dos postes flotantes, unidos al deck por su parte lateral, en lugar de por la base, lo que de da una estática tipo puente. Este sistema aporta la ventaja de dejar un gran espacio para los algodones.

Esta fabricado en acero inoxidable con un mecanizado superior que trasmite calidad y robustez, el Drip Tip es 810 (Tipo GOON) en Delrin para evitar trasmitir el calor a los labios.

Como peculiaridad tiene un sistema de postes con presillas, pero la pletina metálica que fija la resistencia cae hacia abajo por su propio peso a medida que aflojamos, haciendo que la instalación de nuestras resistencias sea más fácil, ademas tiene espacio más que de sobra para instalar resistencias elaboradas.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("VENUS RDA",27.95,"https://morethanvapersshop.es/wp-content/uploads/2018/03/Captura-de-pantalla-2018-04-13-a-las-19.15.22-300x300.jpg",10,"RDA","Venus presenta una apariencia atractiva con un proceso único de grabado. Tiene 24 mm de diámetro con punta de goteo de resina 810. El sistema de flujo de aire lateral y el pozo de aire en ángulo traen una gran nube y un excelente sabor! La plataforma postless proporciona una manera fácil de construir también. También viene con un pin BF para MOD de squonk de alimentación inferior");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("MACE",18.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/1ss-300x300.png",10,"RDA","El MACE BF RDA de Ample es un atomizador de dripeo de24mm de diámetro con una apariencia totalmente única que ciertamente llama la atención. El deck fabricado en acero inoxidable puede usarse en single o dual coil utilizando un sistema de postes con abrazadera de tornillo fija para facilitar la instalación de las resistencias.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("LOOP RDA",24.90,"https://morethanvapersshop.es/wp-content/uploads/2018/04/LOOP-300x300.jpg",10,"RDA","El Loop RDA adopta una plataforma de construcción en forma de W única para el montaje de resistencias dual o single. El sistema de entarada lateral de aire envolvente ajustable proporciona un flujo de aire eficiente y minimiza las fugas. El Loop tiene una regulacion de aire hecha en una sola pieza colocada en una posición fija, asegurando que el aire fluya en la posición correcta");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("VLS OUMIER",22.90,"https://morethanvapersshop.es/wp-content/uploads/2018/04/oumier-vls-rda-1-3-300x300.jpg",10,"RDA","OUMIER VLS RDA es un atomizador reparable innovador con una plataforma de construcción de postes única separada, adecuado para resistencias verticales o horizontales tanto single como duales.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("TOBINHO",20.90,"https://morethanvapersshop.es/wp-content/uploads/2018/04/Captura-de-pantalla-2018-11-08-a-las-11.35.38-300x300.png",10,"RDA","Wismec Luxotic BF kit lleva un atomizador Tobhino BF RDA de goteo, single coil, alimentación inferior de líquido y sistema lateral ajustable de flujo de aire. Al girar la cubierta en un sentido u otro puede variar el flujo de aire para obtener mas sabor o mayor cantidad de vapor. La estructura lleva una base de acero inoxidable, cuenta con rosca 510 y es totalmente desmontable. La plataforma de construcción del atomizador es extremadamente fácil de usar y puede adaptarse a una gran variedad de bobinas. Además el drip tip está fabricado en Ultem, una resina termoresistente que evita el sobrecalentamiento.

Tamaño del kit: 43.2mm x 25.1mm x 100mm. Peso: 143,5 gramos.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("DEAD RABBIT",30.90,"https://morethanvapersshop.es/wp-content/uploads/2018/04/drsqss-300x300.jpg",10,"RDA","El HELLVAPE Dead Rabbit RDA viene con una cubierta de amplia construcción con cuatro tornillos grandes, que es fácil de mecha. Además, puede cortar el alambre debajo de los postes con un alicate de bisel, sin necesidad de cortar el cable de calefacción de antemano. También apoya los alambres de Clapton para la construcción simple o dual de la bobina. Mediante la rotación de la tapa superior, puede ajustar el flujo de aire de su preferencia. El atomizador tiene una punta de goteo de resina, que protege la boca de la combustión, y también hay una punta extra de goteo negro POM en el paquete. 
");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("DOTTANK",70.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/dotmod-rta-tank-4-500x500-300x300.png",10,"RTA","Nuevo atomizador de DotMod, el Dot Tank 24mm es un claromizador de resistencias comerciales intercambiables.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("MANTA",32.40,"https://morethanvapersshop.es/wp-content/uploads/2018/07/1179879610_w800_h640_silver.800x800-300x300.jpg",10,"RTA","El Advken MANTA RTA es un atomizador RTA de doble serpent, con postes curvos y con una capacidad de 2ml en 24mm de diámetro. Sistema único de control de flujo de aire, postes positivos y negativos chapados en oro al vacío, punta de goteo 810 PEI y fácil llenado de la parte superior.

");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("KYLIN",39.95,"https://morethanvapersshop.es/wp-content/uploads/2018/11/Captura-de-pantalla-2018-11-23-a-las-12.54.51-300x300.jpg",10,"RTA","Uno de los atomizadores más esperados del momento, Kylin RTA de Vandy Vape, 24mm de diametro en su base y 26mm en el cuerpo, incluye 2 depositos de 2 y 6ml, posibilidad de single y dual, diseñado para grandes vaporadas y sabor espectacular gracias a su doble subida de aire.

 ");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("BOMBUS",18.90,"https://morethanvapersshop.es/wp-content/uploads/2019/02/BombusBlack-300x300.jpg",10,"RTA","Un nuevo atomizador reparable con tanque y soporte para resistencias single coil. La entrada de aire ajustable proporciona un agradable sabor y la entrada de líquido es muy cómoda con su puerta deslizante.

Este BOMBUS RTA es la apuesta de OUMIER para todo tipo de vapeadores.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("DOT RDTA",65.90,"https://morethanvapersshop.es/wp-content/uploads/2018/05/dotrdtaultem-300x300.jpg",10,"RDTA","Dot RDTA de DotMod, con un diseño espectacular, una construcción muy solida y una clavija bañada en oro de 24k con la que tendrás un montaje de resistencias muy comodo e intuitivo. La forma de rellenado es muy simple e incluye Pin BF para usar en tu Mod Squonk");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("TAUREN MOD",42.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/b46e08eaf2-300x300.jpg",10,"MOD","Mod Mecanico de alta calidad fabricado por Thunderhead Creations, dependiendo el acabado su material es latón o cobre, ambos muy conductivos y de gran grosor lo que da un extra de conductividad, pulsador muy innovador y de grandes prestaciones, perfecto para atomizadores de 24 y 25mm y valido para baterias 18650, 20700 y 21700. (No Incluidas)");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("VGOD PRO MECH",94.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/lifestylepicture_02-copia-1-300x300.jpg",3,"MOD","El MOD de MECH VGOD PRO es un nuevo y vibrante miembro de la familia de VGOD! Construidos de cobre duradero y cuerpo de acero inoxidable tratado con una capa de pintura mate de altísima calidad (roja,blanco o negro) , y rematado con el grabado oficial de VGOD, que aporta elegancia al MOD de VGOD MECH , diferenciandote del resto con un producto exclusivo.
Mod Mecanico
Mod tubular de 24mm
Sin Nicotina
Puedes Tenerlo De Pie Sin Miedo A Pulsarlo Accidentalmente");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("SUB OHM INNOVATIONS",250.90,"https://morethanvapersshop.es/wp-content/uploads/2018/04/soi-brushed-spec-ed-bn-300x300.png",10,"MOD","Sub Ohm Innovations nos presenta el SOI Brushed edition, un kit hecho para vapeadores expertos amantes de la calidad, existen un número limitado de unidades.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("ASMODUS COLOSSAL 80W",51.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/pink-1_large_a403c85b-ff3b-44f1-b62e-df765164023e_large-300x300.jpg",10,"MOD","Asmodus nos presenta su nuevo Mod de una sola batería (No Incluida) dispone de varios modos para desbloquear la pantalla, pudiendo elegir entre deslizar la pantalla hacia abajo o darle tres toques a la pantalla. 
El Colossal, dispone de una Conexión segura para la batería propia de Asmodus. Además cuenta con un puerto USB para la actualización del Firmware. No carga por USB");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("DREAMER MOD MECH NAVAL TIMESVAPES",70.40,"https://morethanvapersshop.es/wp-content/uploads/2018/05/authentic-timesvape-dreamer-hybrid-mechanical-mod-brass-brass-1-x-18650-20700-21700-1-300x300.jpg",10,"MOD","El Dreamer ya está aquí! Diseñado en EE.UU y manufacturado por la prestigiosa marca Timesvapes.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("K STRAWBERRY",17,"https://morethanvapersshop.es/wp-content/uploads/2018/03/k_2-300x300.jpg",10,"MOD","La nostalgia de la tienda de chuches de tu infancia y la fresa fresca se funden en este fantástico eliquid de fresa loca. Una fresa cremosa que no te cansarás de vapear.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("POPDEEZ 50ml",18.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/pop-deez-steep-vapors-300x300.jpg",10,"LIQUIDO","Este liquido es un secreto, Pruebalo te gustara");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("BEBECA",15.95,"https://morethanvapersshop.es/wp-content/uploads/2018/03/atmos-lab-bebeca-60ml-300x300.jpg",10,"LIQUIDO","Sin lugar a dudas BEBECA es el sabor estrella de Atmos Lab. Sabor a auténtico cigarrillo, vainilla y natilla se combinan para producir un increíble líquido de vapeo. Para muchos, el auténtico Alter Ego del famoso Tribeca de Halo.

PROPORCION PG/VG:
50/50
ENVASE: 
Botella 10ml PET transparente, obturador cuentagotas, tapón con evidencia de manipulación y de seguridad a prueba de niños (ISO 8317) y triangulo táctil de advertencia a invidentes (ISO 11683).");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("BIG MOLLY",22.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/5343-large_default-300x300.jpg",10,"LIQUIDO","Donut recien horneado, nunca has probado un chocolate asi");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("Jellynut",18.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/jellynut-corona-brother-1-300x300.jpg",10,"LIQUIDO","Líquido con el sabor característico de la granada dulce mezclada con la acidez del arándano azul y una deliciosa crema.");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("Croissant",22.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/Captura-de-pantalla-2018-04-01-a-las-14.33.15-2-300x300.png",10,"LIQUIDO","Liquido sabor croissant, para los mas golosos , DIRECTO DESDE EL HORNO AL PALADAR");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("PACHAMAMA",19.90,"https://morethanvapersshop.es/wp-content/uploads/2018/03/pacha-mama-by-charlies-chalk-dust-mango-pitaya-and-pineapple-short-fill_1024x1024-300x300.jpg",10,"LIQUIDO","Liquido tropical,Estaras tomandotelo en las bahamas");
INSERT INTO productos(nombre,precio,imagen,stock,categoria,descripcion ) VALUES ("TARIFA",15.40,"https://morethanvapersshop.es/wp-content/uploads/2018/03/Captura-de-pantalla-2018-03-30-a-las-22.05.14-300x300.png",1,"LIQUIDO","Imagínate sentado en una terraza frente al mar con un cóctel de frutas.. Que maravillosa sensación !!!

Tarifa, es una armoniosa combinación de Naranjas Amargas y Dulces con un final refrescante, con la que pasarás horas y horas vapeando sin cansarte.");
INSERT INTO detallePedido ( estado, productos, precio) VALUES ( 'Confirmado', 'DRUGA,subOHm', '254');
INSERT INTO detallePedido ( estado, productos, precio) VALUES ('Cancelado', 'Druga,NanoWASp', '63.63');


